[CI] Fix macOS
The macOS build was failing with:

  * installing *source* package ‘xts’ ...
  ** using staged installation
  ** libs
  clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/zoo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c add_class.c -o add_class.o
  clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
  In file included from add_class.c:23:
  /Library/Frameworks/R.framework/Resources/include/R.h:55:11: fatal error: 'stdlib.h' file not found
  # include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
            ^
  1 error generated.
  make: *** [add_class.o] Error 1
  ERROR: compilation failed for package ‘xts’

I found the solution here:

  https://travis-ci.community/t/library-developer-commandlinetools-sdks-macosx-sdk-missing-on-el-capitain/3213